/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterfacePatient;

import Hospital.Ecosystem;
import Model.Appointments;
import Model.Lab_Reports;
import Model.OperationRequest;
import Roles.Doctor;
import Roles.Patient;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumanayanakonda
 */
public class ReportsPatient extends javax.swing.JPanel {
Ecosystem ecoSystem;
Patient patient;
    /**
     * Creates new form ReportsPatient
     */
    public ReportsPatient(Ecosystem  ecoSystem, Patient patient) {
        initComponents();
        this. ecoSystem= ecoSystem;
        this.patient = patient;
        TableFilling();
        TableFilling2();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        oper = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lab = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        oper.setBackground(new java.awt.Color(153, 153, 255));
        oper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Inference", "Operation Room", "Date", "Doctor", "Status"
            }
        ));
        jScrollPane2.setViewportView(oper);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Operation Reports", jPanel2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lab.setBackground(new java.awt.Color(153, 153, 255));
        lab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Blood Type", "Hemogoblin Levels", "Blood Count", "EEG levels", "Sugar Level"
            }
        ));
        jScrollPane1.setViewportView(lab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lab Reports", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable lab;
    private javax.swing.JTable oper;
    // End of variables declaration//GEN-END:variables

    private void TableFilling() {
    
        
    
     DefaultTableModel model = (DefaultTableModel) lab.getModel();
        model.setRowCount(0);
        System.out.println("pop table");
        System.out.println(ecoSystem.getLabreportsdir().getLabReportsList().size());
        System.out.println(ecoSystem.getPatientdir().getPatientList().size());
        for(Lab_Reports en : ecoSystem.getLabreportsdir().getLabReportsList()){
             if (patient.getEmailId().equals(en.getPatient().getEmailId())){
               
            Object[] row = new Object[6];
            row[0] = en.getDateitsdone();
            row[1] = en.getBloodType();
            row[2] = en.getHemogoblinLevels();
            row[3] = en.getBloodCount();
            row[4] = en.getEEG_Levels();
            row[5] = en.getSugarLevels();
            
            model.addRow(row);
            
             }}}

    private void TableFilling2() {
        
     DefaultTableModel model = (DefaultTableModel) oper.getModel();
        model.setRowCount(0);
        for(OperationRequest en : ecoSystem.getOperationsbookingdir().getOpRequestList())
             if (patient.getEmailId().equals(en.getPatient().getEmailId())){
            {    
            Object[] row = new Object[5];
            row[0] = en.getInference();
            row[1] = en.getOperationRoom();
            row[2] = en.getDateofOperation();
            row[3] = en.getDoctor().getFirstName()+" "+en.getDoctor().getLastName();
            //row[4] = en.get;
            row[4] = en.getStatus();
            model.addRow(row);
            }
             }
    
    }
}
